INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project 1", "example", 1000, "monday", "friday");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project 2", "example", 1000, "monday", "friday");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project 3", "example", 1000, "monday", "friday");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project 4", "example", 1000, "monday", "friday");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project 5", "example", 1000, "monday", "friday");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project 6", "example", 1000, "monday", "friday");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project 7", "example", 1000, "monday", "friday");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project 8", "example", 1000, "monday", "friday");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project 9", "example", 1000, "monday", "friday");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project 10", "example", 1000, "monday", "friday");

INSERT INTO users (name, age) VALUES ("dude 1", 22);
INSERT INTO users (name, age) VALUES ("dude 2", 22);
INSERT INTO users (name, age) VALUES ("dude 3", 22);
INSERT INTO users (name, age) VALUES ("dude 4", 22);
INSERT INTO users (name, age) VALUES ("dude 5", 22);
INSERT INTO users (name, age) VALUES ("dude 6", 22);
INSERT INTO users (name, age) VALUES ("dude 7", 22);
INSERT INTO users (name, age) VALUES ("dude 8", 22);
INSERT INTO users (name, age) VALUES ("dude 9", 22);
INSERT INTO users (name, age) VALUES ("dude 10", 22);
INSERT INTO users (name, age) VALUES ("dude 11", 22);
INSERT INTO users (name, age) VALUES ("dude 12", 22);
INSERT INTO users (name, age) VALUES ("dude 13", 22);
INSERT INTO users (name, age) VALUES ("dude 14", 22);
INSERT INTO users (name, age) VALUES ("dude 15", 22);
INSERT INTO users (name, age) VALUES ("dude 16", 22);
INSERT INTO users (name, age) VALUES ("dude 17", 22);
INSERT INTO users (name, age) VALUES ("dude 18", 22);
INSERT INTO users (name, age) VALUES ("dude 19", 22);
INSERT INTO users (name, age) VALUES ("dude 20", 22);

INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 5, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 6, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 11, 11);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 12, 12);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 13, 13);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 14, 14);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 15, 15);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 16, 16);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 17, 17);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 18, 18);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 19, 19);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 20, 20);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 5, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 6, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 10, 10);
