INSERT INTO users(name) VALUES ("Anne Adams");
INSERT INTO users(name) VALUES ("Bob Brown");
INSERT INTO users(name) VALUES ("Cathy Connors");
INSERT INTO users(name) VALUES ("Daniel Davidson");
INSERT INTO users(name) VALUES ("Emily Estevez");
INSERT INTO users(name) VALUES ("Fred Farmington");
INSERT INTO users(name) VALUES ("Greta Garbo");
INSERT INTO users(name) VALUES ("Henry Hanks");
INSERT INTO users(name) VALUES ("Indira Ingram");
INSERT INTO users(name) VALUES ("Jimmy Jackson");
INSERT INTO users(name) VALUES ("Kelly Kapstone");
INSERT INTO users(name) VALUES ("Lonnie Livingston");
INSERT INTO users(name) VALUES ("Marsha Mathers");
INSERT INTO users(name) VALUES ("Ned Nelson");
INSERT INTO users(name) VALUES ("Octavia Overton");
INSERT INTO users(name) VALUES ("Peter Phillips");
INSERT INTO users(name) VALUES ("Rosa Rodriguez");
INSERT INTO users(name) VALUES ("Scoot Sampson");
INSERT INTO users(name) VALUES ("Tina Turner");
INSERT INTO users(name) VALUES ("Umlaut Unger");


INSERT INTO projects(title,category,funding_goal) VALUES ("Bring Anne to Argentina","music",500000);
INSERT INTO projects(title,category,funding_goal) VALUES ("Bring Bob to Bolivia","music",500000);
INSERT INTO projects(title,category,funding_goal) VALUES ("Bring Cathy to Canada","music",40000);
INSERT INTO projects(title,category,funding_goal) VALUES ("Bring Daniel to Denmark","books",40000);
INSERT INTO projects(title,category,funding_goal) VALUES ("Bring Emily to Estonia","books",40000);
INSERT INTO projects(title,category,funding_goal) VALUES ("Bring Fred to France","books",3000);
INSERT INTO projects(title,category,funding_goal) VALUES ("Bring Greta to Gabon","books",3000);
INSERT INTO projects(title,category,funding_goal) VALUES ("Bring Henry to Haiti","books",3000);
INSERT INTO projects(title,category,funding_goal) VALUES ("Bring Indira to India","music",6000000);
INSERT INTO projects(title,category,funding_goal) VALUES ("Bring Jimmy to Jamaica","music",6000000);

INSERT INTO pledges(amount,project_id,user_id) VALUES (500,10,1);
INSERT INTO pledges(amount,project_id,user_id) VALUES (500,9,2);
INSERT INTO pledges(amount,project_id,user_id) VALUES (500,8,3);
INSERT INTO pledges(amount,project_id,user_id) VALUES (500,7,4);
INSERT INTO pledges(amount,project_id,user_id) VALUES (500,6,5);
INSERT INTO pledges(amount,project_id,user_id) VALUES (500,5,6);
INSERT INTO pledges(amount,project_id,user_id) VALUES (500,4,7);
INSERT INTO pledges(amount,project_id,user_id) VALUES (500,3,8);
INSERT INTO pledges(amount,project_id,user_id) VALUES (500,2,9);
INSERT INTO pledges(amount,project_id,user_id) VALUES (500,1,10);
INSERT INTO pledges(amount,project_id,user_id) VALUES (500,2,11);
INSERT INTO pledges(amount,project_id,user_id) VALUES (500,3,12);
INSERT INTO pledges(amount,project_id,user_id) VALUES (500,4,13);
INSERT INTO pledges(amount,project_id,user_id) VALUES (500,5,14);
INSERT INTO pledges(amount,project_id,user_id) VALUES (500,6,15);
INSERT INTO pledges(amount,project_id,user_id) VALUES (500,7,16);
INSERT INTO pledges(amount,project_id,user_id) VALUES (500,8,17);
INSERT INTO pledges(amount,project_id,user_id) VALUES (500,9,18);
INSERT INTO pledges(amount,project_id,user_id) VALUES (500,10,19);
INSERT INTO pledges(amount,project_id,user_id) VALUES (500,9,20);
INSERT INTO pledges(amount,project_id,user_id) VALUES (500,8,19);
INSERT INTO pledges(amount,project_id,user_id) VALUES (500,7,18);
INSERT INTO pledges(amount,project_id,user_id) VALUES (500,6,17);
INSERT INTO pledges(amount,project_id,user_id) VALUES (500,5,16);
INSERT INTO pledges(amount,project_id,user_id) VALUES (500,4,15);
INSERT INTO pledges(amount,project_id,user_id) VALUES (500,3,14);
INSERT INTO pledges(amount,project_id,user_id) VALUES (500,2,13);
INSERT INTO pledges(amount,project_id,user_id) VALUES (500,1,12);
INSERT INTO pledges(amount,project_id,user_id) VALUES (500,2,11);
INSERT INTO pledges(amount,project_id,user_id) VALUES (500,3,10);
